<a href="https://colab.research.google.com/github/pamumeghana45-cell/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# a. Help on the add function
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [2]:
# b. Test whether none of the elements of a given array is zero
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print("None of the elements is zero:", np.all(arr1 != 0))


None of the elements is zero: True


In [3]:
# c. Element-wise comparison of two arrays
import numpy as np
arr2 = np.array([2, 2, 3, 5])
print("Greater:", np.greater(arr1, arr2))
print("Greater Equal:", np.greater_equal(arr1, arr2))
print("Less:", np.less(arr1, arr2))
print("Less Equal:", np.less_equal(arr1, arr2))
print("Equal:", np.equal(arr1, arr2))
print("Equal within tolerance:", np.allclose(arr1, arr2, atol=1))
# Convert to list
print("Array to list:", arr1.tolist())



Greater: [False False False False]
Greater Equal: [False  True  True False]
Less: [ True False False  True]
Less Equal: [ True  True  True  True]
Equal: [False  True  True False]
Equal within tolerance: True
Array to list: [1, 2, 3, 4]


In [4]:
# Sample array
arr = np.array([[10, 20, 5], [30, 15, 25]])
# a. Extract numbers less than and greater than a specified number
specified_number = 18
less_than = arr[arr < specified_number]
greater_than = arr[arr > specified_number]
print("Less than 18:", less_than)
print("Greater than 18:", greater_than)


Less than 18: [10  5 15]
Greater than 18: [20 30 25]


In [6]:
 #b. Indices of max and min along axis
import numpy as np
# Create a sample 2D NumPy array
arr = np.array([[10, 20, 5],
                [15, 3, 25],
                [30, 8, 12]])

print("Original array:")
print(arr)

# Find the indices of the maximum values along each row (axis=1)
max_indices = np.argmax(arr, axis=1)

# Find the indices of the minimum values along each row (axis=1)
min_indices = np.argmin(arr, axis=1)

print("\nIndices of the maximum values along each row:", max_indices)
print("Indices of the minimum values along each row:", min_indices)

# To verify, you can use these indices to get the actual max and min values
max_values = arr[np.arange(len(arr)), max_indices]
min_values = arr[np.arange(len(arr)), min_indices]

print("\nMaximum values:", max_values)
print("Minimum values:", min_values)


Original array:
[[10 20  5]
 [15  3 25]
 [30  8 12]]

Indices of the maximum values along each row: [1 2 0]
Indices of the minimum values along each row: [2 1 1]

Maximum values: [20 25 30]
Minimum values: [5 3 8]
